In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
print(x)

x[0] = 100
print(x)

[1 2 3]
[100   2   3]


In [3]:
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
y = np.arange(5,15)
print(y)

[ 5  6  7  8  9 10 11 12 13 14]


In [5]:
a = np.array([1,2,3,4,5])
b = a
print('a=' + str(a) + 'b=' + str(b))

a[0] = 100
print('a=' + str(a) + 'b=' + str(b))

a=[1 2 3 4 5]b=[1 2 3 4 5]
a=[100   2   3   4   5]b=[100   2   3   4   5]


In [7]:
a = np.array([1,2,3,4,5])
b = a.copy()
print('a=' + str(a) + ' b=' + str(b))

a[0] = 100
print('a=' + str(a) + 'b=' + str(b))

a=[1 2 3 4 5] b=[1 2 3 4 5]
a=[100   2   3   4   5]b=[1 2 3 4 5]


In [8]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [9]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [10]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

w,h = x.shape

print(w)
print(h)

[[1 2 3]
 [4 5 6]]
2
3


In [11]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

print(x[0,0])
print(x[1,1])

x[0,0] = 100
print(x)

[[1 2 3]
 [4 5 6]]
1
5
[[100   2   3]
 [  4   5   6]]


In [12]:
x = np.zeros(2)
print(x)

[0. 0.]


In [14]:
y = np.zeros((2,2))
print(y)

[[0. 0.]
 [0. 0.]]


In [15]:
z = np.zeros((2,2,2))
print(z)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [16]:
x = np.ones(2)
print(x)

[1. 1.]


In [17]:
y = np.ones((2,2))
print(y)

[[1. 1.]
 [1. 1.]]


In [18]:
x = np.random.rand(5)
print(x)

[0.59670195 0.42313687 0.00111312 0.16811277 0.4449491 ]


In [19]:
y = np.random.rand(5,2)
print(y)

[[0.45321177 0.76761919]
 [0.17031465 0.9951249 ]
 [0.66609311 0.33392038]
 [0.20106641 0.9774904 ]
 [0.56175346 0.54123407]]


In [20]:
a = np.array([1,2,3,4])
print(a)

b = a.reshape(2,2)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]


In [21]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print('x=' + str(x))
print('y=' + str(y))

x=[[1 2]
 [3 4]]
y=[[5 6]
 [7 8]]


In [22]:
print(x+y)

[[ 6  8]
 [10 12]]


In [23]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [24]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,3,],[4,5],[6,7]])
print('x=' + str(x))
print('y=' + str(y))

x=[[1 2 3]
 [4 5 6]]
y=[[2 3]
 [4 5]
 [6 7]]


In [25]:
print(x.dot(y))

[[28 34]
 [64 79]]


In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print('x=' + str(x))
print('y=' + str(y))


x=[[1 2]
 [3 4]]
y=[[5 6]
 [7 8]]


In [27]:
print(x*y)

[[ 5 12]
 [21 32]]


In [28]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print('x=' + str(x))
print('y=' + str(y))

x=[[1 2]
 [3 4]]
y=[[5 6]
 [7 8]]


In [29]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [30]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print(x[1:3])

[1 2]


In [32]:
print(x[:4])

[0 1 2 3]


In [34]:
print(x[3:])

[3 4 5 6 7 8 9]


In [35]:
print(x[3:8:2])

[3 5 7]


In [36]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [37]:
x = np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [38]:
x[x>3]

array([ 5,  8, 13])

In [40]:
x[x>3] = 999
print(x)

[  1   1   2   3 999 999 999]


In [41]:
def my_fun1() :
    print('Hi! This is my first function.')
    
my_fun1()

Hi! This is my first function.


In [42]:
def my_fun2(a,b) :
    c = a + b
    return c

my_fun2(2,10)

12

In [46]:
def my_fun3(d) :
    m = np.mean(d)
    s = np.std(d)
    return m, s

data = np.random.randn(200)
data_mean, data_std = my_fun3(data)
print('Mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean,data_std))

Mean:-0.06, std:0.95


In [48]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy',data)
data=[]
print(data)
data=np.load('datafile.npy')
print(data)

[-1.1371651   0.18698921  0.27065343  1.78908715  1.3205951 ]
[]
[-1.1371651   0.18698921  0.27065343  1.78908715  1.3205951 ]


In [49]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz',data1=data1, data2=data2)
data1=[]
data2=[]
outfile=np.load('datafile2.npz')
print(outfile.files)
data1=outfile['data1']
data2=outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]


In [50]:
x1 = np.arange(0,10,2)
print(x1)

[0 2 4 6 8]


In [52]:
x2 = np.linspace(0,10,10)
print(x2)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
